# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('source_perc', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.NewsSource'),
        ),
    ]
