# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='source_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
