# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_newssource_source_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsfeed',
            old_name='source',
            new_name='NewsSource',
        ),
    ]
