# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20180426_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsfeed',
            old_name='NewsSource',
            new_name='source',
        ),
    ]
